- name: Hello world
  hosts: debian-desktop
  gather_facts: no
  become: yes
  roles:
    - name: user-access
      user_access_username: user
      user_access_password: Password123
      
  tasks:
    - name: Print hello world
      debug:
        msg: "Hello World"
